name: Build & Publish Docker (GHCR)

on:
  push:
    branches: [ main ]        # change to [ master ] if repo uses master
    tags: ['v*', 'release-*']
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set image name (lowercase)
        shell: bash
        run: |
          echo "IMAGE_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
          echo "IMAGE_REPO=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV
          echo "IMAGE=ghcr.io/${IMAGE_OWNER}/${IMAGE_REPO,,}" >> $GITHUB_ENV
          echo "Resolved image: ${IMAGE}"

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
